In [238]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [239]:
Train = pd.read_csv("train.csv")
Test = pd.read_csv("test.csv")

In [240]:
Train.shape

(550068, 12)

In [241]:
Test.shape

(233599, 11)

In [242]:
Train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550068 entries, 0 to 550067
Data columns (total 12 columns):
User_ID                       550068 non-null int64
Product_ID                    550068 non-null object
Gender                        550068 non-null object
Age                           550068 non-null object
Occupation                    550068 non-null int64
City_Category                 550068 non-null object
Stay_In_Current_City_Years    550068 non-null object
Marital_Status                550068 non-null int64
Product_Category_1            550068 non-null int64
Product_Category_2            376430 non-null float64
Product_Category_3            166821 non-null float64
Purchase                      550068 non-null int64
dtypes: float64(2), int64(5), object(5)
memory usage: 50.4+ MB

In [243]:
Test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233599 entries, 0 to 233598
Data columns (total 11 columns):
User_ID                       233599 non-null int64
Product_ID                    233599 non-null object
Gender                        233599 non-null object
Age                           233599 non-null object
Occupation                    233599 non-null int64
City_Category                 233599 non-null object
Stay_In_Current_City_Years    233599 non-null object
Marital_Status                233599 non-null int64
Product_Category_1            233599 non-null int64
Product_Category_2            161255 non-null float64
Product_Category_3            71037 non-null float64
dtypes: float64(2), int64(4), object(5)
memory usage: 19.6+ MB

In [244]:
Train['Product_Category_3'].unique()

array([nan, 14., 17.,  5.,  4., 16., 15.,  8.,  9., 13.,  6., 12.,  3.,
       18., 11., 10.])

In [245]:
Train['Product_Category_2'][Train['Product_Category_2'].isnull()] = 0
Train['Product_Category_3'][Train['Product_Category_3'].isnull()] = 0
Test['Product_Category_2'][Test['Product_Category_2'].isnull()] = 0
Test['Product_Category_3'][Test['Product_Category_3'].isnull()] = 0

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [246]:
Train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550068 entries, 0 to 550067
Data columns (total 12 columns):
User_ID                       550068 non-null int64
Product_ID                    550068 non-null object
Gender                        550068 non-null object
Age                           550068 non-null object
Occupation                    550068 non-null int64
City_Category                 550068 non-null object
Stay_In_Current_City_Years    550068 non-null object
Marital_Status                550068 non-null int64
Product_Category_1            550068 non-null int64
Product_Category_2            550068 non-null float64
Product_Category_3            550068 non-null float64
Purchase                      550068 non-null int64
dtypes: float64(2), int64(5), object(5)
memory usage: 50.4+ MB

In [247]:
Test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233599 entries, 0 to 233598
Data columns (total 11 columns):
User_ID                       233599 non-null int64
Product_ID                    233599 non-null object
Gender                        233599 non-null object
Age                           233599 non-null object
Occupation                    233599 non-null int64
City_Category                 233599 non-null object
Stay_In_Current_City_Years    233599 non-null object
Marital_Status                233599 non-null int64
Product_Category_1            233599 non-null int64
Product_Category_2            233599 non-null float64
Product_Category_3            233599 non-null float64
dtypes: float64(2), int64(4), object(5)
memory usage: 19.6+ MB

In [248]:
Test['Purchase'] = 0

In [249]:
Train['Product_ID'] = Train['Product_ID'].str[1:].astype(int)
Test['Product_ID'] = Test['Product_ID'].str[1:].astype(int)

In [250]:
Total = pd.concat([Train,Test],axis=0)

In [251]:
Total

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,69042,F,0-17,10,A,2,0,3,0.0,0.0,8370
1,1000001,248942,F,0-17,10,A,2,0,1,6.0,14.0,15200
2,1000001,87842,F,0-17,10,A,2,0,12,0.0,0.0,1422
3,1000001,85442,F,0-17,10,A,2,0,12,14.0,0.0,1057
4,1000002,285442,M,55+,16,C,4+,0,8,0.0,0.0,7969
5,1000003,193542,M,26-35,15,A,3,0,1,2.0,0.0,15227
6,1000004,184942,M,46-50,7,B,2,1,1,8.0,17.0,19215
7,1000004,346142,M,46-50,7,B,2,1,1,15.0,0.0,15854
8,1000004,97242,M,46-50,7,B,2,1,1,16.0,0.0,15686
9,1000005,274942,M,26-35,20,A,1,1,8,0.0,0.0,7871
10,1000005,251242,M,26-35,20,A,1,1,5,11.0,0.0,5254
11,1000005,14542,M,26-35,20,A,1,1,8,0.0,0.0,3957
12,1000005,31342,M,26-35,20,A,1,1,8,0.0,0.0,6073
13,1000005,145042,M,26-35,20,A,1,1,1,2.0,5.0,15665
14,1000006,231342,F,51-55,9,A,1,0,5,8.0,14.0,5378
15,1000006,190242,F,51-55,9,A,1,0,4,5.0,0.0,2079
16,1000006,96642,F,51-55,9,A,1,0,2,3.0,4.0,13055
17,1000006,58442,F,51-55,9,A,1,0,5,14.0,0.0,8851
18,1000007,36842,M,36-45,1,B,1,1,1,14.0,16.0,11788
19,1000008,249542,M,26-35,12,C,4+,1,1,5.0,15.0,19614
20,1000008,220442,M,26-35,12,C,4+,1,5,14.0,0.0,8584
21,1000008,156442,M,26-35,12,C,4+,1,8,0.0,0.0,9872
22,1000008,213742,M,26-35,12,C,4+,1,8,0.0,0.0,9743
23,1000008,214442,M,26-35,12,C,4+,1,8,0.0,0.0,5982
24,1000008,303442,M,26-35,12,C,4+,1,1,8.0,14.0,11927
25,1000009,135742,M,26-35,17,C,0,0,6,8.0,0.0,16662
26,1000009,39942,M,26-35,17,C,0,0,8,0.0,0.0,5887
27,1000009,161442,M,26-35,17,C,0,0,5,14.0,0.0,6973
28,1000009,78742,M,26-35,17,C,0,0,5,8.0,14.0,5391
29,1000010,85942,F,36-45,1,B,4+,1,2,4.0,8.0,16352
...,...,...,...,...,...,...,...,...,...,...,...,...
233569,1005996,184242,F,26-35,0,B,1,1,9,15.0,0.0,0
233570,1005996,45342,F,26-35,0,B,1,1,1,5.0,17.0,0
233571,1006001,124642,F,26-35,7,A,0,1,16,0.0,0.0,0
233572,1006002,121142,M,51-55,0,C,1,1,8,0.0,0.0,0
233573,1006002,233542,M,51-55,0,C,1,1,1,15.0,0.0,0
233574,1006002,226342,M,51-55,0,C,1,1,11,15.0,0.0,0
233575,1006002,284842,M,51-55,0,C,1,1,1,8.0,17.0,0
233576,1006003,313342,F,46-50,17,C,1,0,5,0.0,0.0,0
233577,1006010,223542,M,36-45,0,C,1,0,1,8.0,17.0,0
233578,1006013,20342,F,26-35,20,C,3,0,1,2.0,0.0,0
233579,1006016,14842,M,46-50,1,B,1,1,1,2.0,5.0,0
233580,1006016,109542,M,46-50,1,B,1,1,8,14.0,17.0,0
233581,1006018,71442,M,36-45,1,C,3,0,15,17.0,0.0,0
233582,1006021,112542,M,26-35,12,B,2,1,1,11.0,15.0,0
233583,1006021,3442,M,26-35,12,B,2,1,4,5.0,8.0,0
233584,1006023,262242,M,26-35,0,C,2,1,1,11.0,16.0,0
233585,1006025,161142,F,26-35,1,B,1,0,11,0.0,0.0,0
233586,1006026,110742,M,36-45,6,C,1,1,1,2.0,8.0,0
233587,1006028,162442,M,18-25,4,A,4+,0,1,16.0,0.0,0
233588,1006030,129842,M,26-35,17,C,1,1,6,8.0,15.0,0
233589,1006030,241442,M,26-35,17,C,1,1,2,15.0,0.0,0
233590,1006032,252442,M,46-50,7,A,3,0,8,0.0,0.0,0
233591,1006033,127642,M,51-55,13,B,1,1,1,2.0,15.0,0
233592,1006035,135742,F,26-35,1,C,3,0,6,8.0,0.0,0
233593,1006036,255442,F,26-35,15,B,4+,1,8,0.0,0.0,0
233594,1006036,118942,F,26-35,15,B,4+,1,8,0.0,0.0,0
233595,1006036,254642,F,26-35,15,B,4+,1,5,8.0,0.0,0
233596,1006036,31842,F,26-35,15,B,4+,1,1,5.0,12.0,0
233597,1006037,124742,F,46-50,1,C,4+,0,10,16.0,0.0,0
233598,1006039,316642,F,46-50,0,B,4+,1,4,5.0,0.0,0

In [252]:
Train.corr(method="pearson")

,User_ID,Product_ID,Occupation,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
User_ID,1.000000,-0.017619,-0.023971,0.020443,0.003825,0.003896,0.003605,0.004716
Product_ID,-0.017619,1.000000,0.009344,0.013194,0.090193,-0.090600,-0.144360,-0.103961
Occupation,-0.023971,0.009344,1.000000,0.024280,-0.007618,0.006712,0.012269,0.020833
Marital_Status,0.020443,0.013194,0.024280,1.000000,0.019888,0.001099,-0.004629,-0.000463
Product_Category_1,0.003825,0.090193,-0.007618,0.019888,1.000000,-0.067877,-0.385534,-0.343703
Product_Category_2,0.003896,-0.090600,0.006712,0.001099,-0.067877,1.000000,0.094750,0.052288
Product_Category_3,0.003605,-0.144360,0.012269,-0.004629,-0.385534,0.094750,1.000000,0.288501
Purchase,0.004716,-0.103961,0.020833,-0.000463,-0.343703,0.052288,0.288501,1.000000

In [253]:
del Total['User_ID']

In [254]:
for i in Train.columns:
    print (Train[i].unique())

[1000001 1000002 1000003 ... 1004113 1005391 1001529]
[ 69042 248942  87842 ... 370293 371644 370853]
['F' 'M']
['0-17' '55+' '26-35' '46-50' '51-55' '36-45' '18-25']
[10 16 15  7 20  9  1 12 17  0  3  4 11  8 19  2 18  5 14 13  6]
['A' 'C' 'B']
['2' '4+' '3' '1' '0']
[0 1]
[ 3  1 12  8  5  4  2  6 14 11 13 15  7 16 18 10 17  9 20 19]
[ 0.  6. 14.  2.  8. 15. 16. 11.  5.  3.  4. 12.  9. 10. 17. 13.  7. 18.]
[ 0. 14. 17.  5.  4. 16. 15.  8.  9. 13.  6. 12.  3. 18. 11. 10.]
[ 8370 15200  1422 ...   135   123   613]

In [255]:
Train = pd.get_dummies(Train)

In [256]:
Train.corr(method='pearson')

,User_ID,Product_ID,Occupation,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,Gender_F,Gender_M,...,Age_51-55,Age_55+,City_Category_A,City_Category_B,City_Category_C,Stay_In_Current_City_Years_0,Stay_In_Current_City_Years_1,Stay_In_Current_City_Years_2,Stay_In_Current_City_Years_3,Stay_In_Current_City_Years_4+
User_ID,1.000000,-0.017619,-0.023971,0.020443,0.003825,0.003896,0.003605,0.004716,0.033474,-0.033474,...,-0.006963,-0.004961,-0.030568,0.019688,0.008272,0.006495,0.019574,0.018551,-0.030953,-0.019567
Product_ID,-0.017619,1.000000,0.009344,0.013194,0.090193,-0.090600,-0.144360,-0.103961,-0.021084,0.021084,...,0.012339,0.013510,-0.003780,-0.008863,0.013068,0.001330,-0.000236,0.003490,-0.000305,-0.004384
Occupation,-0.023971,0.009344,1.000000,0.024280,-0.007618,0.006712,0.012269,0.020833,-0.117291,0.117291,...,0.030846,0.044096,-0.023070,-0.011673,0.034529,-0.026055,-0.002092,-0.012716,0.025974,0.013905
Marital_Status,0.020443,0.013194,0.024280,1.000000,0.019888,0.001099,-0.004629,-0.000463,0.011603,-0.011603,...,0.172278,0.091778,-0.033088,-0.001863,0.033661,-0.010673,0.028831,-0.006474,-0.013635,-0.006782
Product_Category_1,0.003825,0.090193,-0.007618,0.019888,1.000000,-0.067877,-0.385534,-0.343703,0.045594,-0.045594,...,0.025784,0.033925,0.015702,-0.006076,-0.008554,0.004576,0.006121,-0.007000,-0.010995,0.006624
Product_Category_2,0.003896,-0.090600,0.006712,0.001099,-0.067877,1.000000,0.094750,0.052288,0.000954,-0.000954,...,0.009457,0.003799,-0.011200,-0.004534,0.015555,-0.002925,0.001557,0.000494,-0.000637,0.000846
Product_Category_3,0.003605,-0.144360,0.012269,-0.004629,-0.385534,0.094750,1.000000,0.288501,-0.036146,0.036146,...,-0.001806,-0.008228,-0.026976,-0.006270,0.032508,-0.001931,-0.003403,0.004742,0.003398,-0.002331
Purchase,0.004716,-0.103961,0.020833,-0.000463,-0.343703,0.052288,0.288501,1.000000,-0.060346,0.060346,...,0.014792,0.002904,-0.042465,-0.019098,0.061012,-0.006605,-0.002030,0.005358,0.002090,0.000988
Gender_F,0.033474,-0.021084,-0.117291,0.011603,0.045594,0.000954,-0.036146,-0.060346,1.000000,-1.000000,...,0.006416,-0.004921,-0.007299,0.006155,0.000426,-0.016094,0.030400,-0.008806,0.011080,-0.027125
Gender_M,-0.033474,0.021084,0.117291,-0.011603,-0.045594,-0.000954,0.036146,0.060346,-1.000000,1.000000,...,-0.006416,0.004921,0.007299,-0.006155,-0.000426,0.016094,-0.030400,0.008806,-0.011080,0.027125
Age_0-17,-0.029809,0.000990,0.017627,-0.139961,-0.013681,-0.009959,-0.000527,-0.011055,0.034945,-0.034945,...,-0.046093,-0.033889,-0.037945,-0.020552,0.058235,0.005446,-0.009230,0.021599,0.004379,-0.020777
Age_18-25,-0.061903,-0.019640,-0.096659,-0.189174,-0.035036,-0.012391,0.003891,-0.008831,0.000246,-0.000246,...,-0.129045,-0.094879,0.008216,0.013039,-0.021766,0.042822,-0.027666,0.009724,-0.023329,0.010036
Age_26-35,0.039550,-0.014639,-0.022461,-0.027654,-0.018637,-0.003426,0.001772,-0.001830,-0.029811,0.029811,...,-0.223622,-0.164415,0.123752,-0.005266,-0.112852,-0.021607,0.000744,-0.007643,0.014127,0.012900
Age_36-45,0.010785,0.014153,0.058309,-0.013227,0.011429,0.006651,0.001271,0.006707,0.000088,-0.000088,...,-0.137168,-0.100851,-0.030014,0.012556,0.015345,-0.012831,-0.016079,0.008057,0.047259,-0.024780
Age_46-50,0.028149,0.011393,0.020323,0.191389,0.025842,0.008219,-0.002657,-0.003317,0.029262,-0.029262,...,-0.082580,-0.060716,-0.069342,0.016007,0.049315,0.009858,0.024941,-0.009156,-0.033426,0.002550
Age_51-55,-0.006963,0.012339,0.030846,0.172278,0.025784,0.009457,-0.001806,0.014792,0.006416,-0.006416,...,1.000000,-0.055334,-0.068173,0.022526,0.041245,-0.017238,0.050712,-0.018785,-0.030997,0.001930
Age_55+,-0.004961,0.013510,0.044096,0.091778,0.033925,0.003799,-0.008228,0.002904,-0.004921,0.004921,...,-0.055334,1.000000,-0.046599,-0.073642,0.123121,0.000042,-0.008210,0.002918,-0.002157,0.009946
City_Category_A,-0.030568,-0.003780,-0.023070,-0.033088,0.015702,-0.011200,-0.026976,-0.042465,-0.007299,0.007299,...,-0.068173,-0.046599,1.000000,-0.515898,-0.407268,0.050357,-0.023573,-0.002476,-0.008505,-0.004932
City_Category_B,0.019688,-0.008863,-0.011673,-0.001863,-0.006076,-0.004534,-0.006270,-0.019098,0.006155,-0.006155,...,0.022526,-0.073642,-0.515898,1.000000,-0.572277,-0.027782,0.015090,-0.009736,0.025754,-0.010174
City_Category_C,0.008272,0.013068,0.034529,0.033661,-0.008554,0.015555,0.032508,0.061012,0.000426,-0.000426,...,0.041245,0.123121,-0.407268,-0.572277,1.000000,-0.018587,0.006478,0.012750,-0.019316,0.015569
Stay_In_Current_City_Years_0,0.006495,0.001330,-0.026055,-0.010673,0.004576,-0.002925,-0.001931,-0.006605,-0.016094,0.016094,...,-0.017238,0.000042,0.050357,-0.027782,-0.018587,1.000000,-0.291711,-0.188509,-0.181025,-0.168752
Stay_In_Current_City_Years_1,0.019574,-0.000236,-0.002092,0.028831,0.006121,0.001557,-0.003403,-0.002030,0.030400,-0.030400,...,0.050712,-0.008210,-0.023573,0.015090,0.006478,-0.291711,1.000000,-0.351584,-0.337625,-0.314736
Stay_In_Current_City_Years_2,0.018551,0.003490,-0.012716,-0.006474,-0.007000,0.000494,0.004742,0.005358,-0.008806,0.008806,...,-0.018785,0.002918,-0.002476,-0.009736,0.012750,-0.188509,-0.351584,1.000000,-0.218180,-0.203389
Stay_In_Current_City_Years_3,-0.030953,-0.000305,0.025974,-0.013635,-0.010995,-0.000637,0.003398,0.002090,0.011080,-0.011080,...,-0.030997,-0.002157,-0.008505,0.025754,-0.019316,-0.181025,-0.337625,-0.218180,1.000000,-0.195314
Stay_In_Current_City_Years_4+,-0.019567,-0.004384,0.013905,-0.006782,0.006624,0.000846,-0.002331,0.000988,-0.027125,0.027125,...,0.001930,0.009946,-0.004932,-0.010174,0.015569,-0.168752,-0.314736,-0.203389,-0.195314,1.000000

In [257]:
Train['Occupation'] = Train['Occupation'].astype('category')

In [258]:
Train = pd.get_dummies(Train)

In [259]:
Train.corr(method='pearson')

,User_ID,Product_ID,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,Gender_F,Gender_M,Age_0-17,...,Occupation_11,Occupation_12,Occupation_13,Occupation_14,Occupation_15,Occupation_16,Occupation_17,Occupation_18,Occupation_19,Occupation_20
User_ID,1.000000,-0.017619,0.020443,0.003825,0.003896,0.003605,0.004716,0.033474,-0.033474,-0.029809,...,-0.018327,-0.015302,-0.027008,0.023269,0.036969,0.005952,0.000178,0.006981,-0.029552,-0.023785
Product_ID,-0.017619,1.000000,0.013194,0.090193,-0.090600,-0.144360,-0.103961,-0.021084,0.021084,0.000990,...,0.002151,-0.000481,0.010099,-0.001841,-0.002054,0.006688,0.003999,0.005312,-0.003145,0.001057
Marital_Status,0.020443,0.013194,1.000000,0.019888,0.001099,-0.004629,-0.000463,0.011603,-0.011603,-0.139961,...,-0.007730,0.027601,0.029281,0.001018,0.013363,0.028370,0.012910,0.009975,-0.058008,0.040947
Product_Category_1,0.003825,0.090193,0.019888,1.000000,-0.067877,-0.385534,-0.343703,0.045594,-0.045594,-0.013681,...,0.007070,-0.014237,0.020272,-0.007123,-0.004792,0.006437,-0.024783,0.005509,0.003590,0.017229
Product_Category_2,0.003896,-0.090600,0.001099,-0.067877,1.000000,0.094750,0.052288,0.000954,-0.000954,-0.009959,...,-0.002619,0.009134,0.002397,0.007263,0.002254,0.003060,0.009632,-0.003532,-0.000013,-0.007812
Product_Category_3,0.003605,-0.144360,-0.004629,-0.385534,0.094750,1.000000,0.288501,-0.036146,0.036146,-0.000527,...,-0.005543,0.017710,-0.006602,0.002857,0.008136,-0.004624,0.029622,-0.000753,-0.004603,-0.015074
Purchase,0.004716,-0.103961,-0.000463,-0.343703,0.052288,0.288501,1.000000,-0.060346,0.060346,-0.011055,...,-0.001464,0.025995,0.001007,0.010772,0.015416,0.005713,0.031099,-0.002073,-0.013769,-0.021693
Gender_F,0.033474,-0.021084,0.011603,0.045594,0.000954,-0.036146,-0.060346,1.000000,-1.000000,0.034945,...,-0.039946,-0.077104,-0.014687,0.000399,-0.017588,-0.043355,-0.096675,-0.054313,-0.002466,0.009242
Gender_M,-0.033474,0.021084,-0.011603,-0.045594,-0.000954,0.036146,0.060346,-1.000000,1.000000,-0.034945,...,0.039946,0.077104,0.014687,-0.000399,0.017588,0.043355,0.096675,0.054313,0.002466,-0.009242
Age_0-17,-0.029809,0.000990,-0.139961,-0.013681,-0.009959,-0.000527,-0.011055,0.034945,-0.034945,1.000000,...,-0.023251,-0.029783,-0.018638,-0.033639,-0.025267,-0.036946,-0.045580,-0.018547,0.051955,-0.042829
Age_18-25,-0.061903,-0.019640,-0.189174,-0.035036,-0.012391,0.003891,-0.008831,0.000246,-0.000246,-0.079034,...,-0.045430,-0.021717,-0.056151,-0.012164,-0.041661,-0.062572,-0.060150,-0.004967,0.037090,-0.012535
Age_26-35,0.039550,-0.014639,-0.027654,-0.018637,-0.003426,0.001772,-0.001830,-0.029811,0.029811,-0.136957,...,0.009924,0.045469,-0.097303,0.043481,0.050933,-0.054121,0.015415,-0.013632,0.002726,0.009244
Age_36-45,0.010785,0.014153,-0.013227,0.011429,0.006651,0.001271,0.006707,0.000088,-0.000088,-0.084008,...,0.013129,0.012033,-0.043196,0.002683,0.004698,0.054123,0.039246,0.008444,-0.025268,0.015108
Age_46-50,0.028149,0.011393,0.191389,0.025842,0.008219,-0.002657,-0.003317,0.029262,-0.029262,-0.050576,...,0.028504,-0.002832,-0.000619,-0.024983,-0.007018,0.029019,0.033849,0.034657,-0.023654,-0.002460
Age_51-55,-0.006963,0.012339,0.172278,0.025784,0.009457,-0.001806,0.014792,0.006416,-0.006416,-0.046093,...,0.028387,-0.023583,0.075320,-0.029505,-0.016351,0.072772,-0.007535,0.004411,-0.022709,0.022800
Age_55+,-0.004961,0.013510,0.091778,0.033925,0.003799,-0.008228,0.002904,-0.004921,0.004921,-0.033889,...,-0.020245,-0.036381,0.364044,0.011547,-0.002779,0.043429,-0.000268,-0.012632,-0.008671,-0.020027
City_Category_A,-0.030568,-0.003780,-0.033088,0.015702,-0.011200,-0.026976,-0.042465,-0.007299,0.007299,-0.037945,...,-0.018322,-0.022938,-0.058633,0.007765,-0.006468,-0.014048,-0.040679,-0.006519,-0.001206,0.063920
City_Category_B,0.019688,-0.008863,-0.001863,-0.006076,-0.004534,-0.006270,-0.019098,0.006155,-0.006155,-0.020552,...,0.018617,0.001284,-0.026781,-0.003746,0.003744,0.003802,-0.010173,-0.022187,-0.004664,0.004542
City_Category_C,0.008272,0.013068,0.033661,-0.008554,0.015555,0.032508,0.061012,0.000426,-0.000426,0.058235,...,-0.002309,0.020589,0.084680,-0.003439,0.002200,0.009394,0.049786,0.029895,0.006127,-0.066032
Stay_In_Current_City_Years_0,0.006495,0.001330,-0.010673,0.004576,-0.002925,-0.001931,-0.006605,-0.016094,0.016094,0.005446,...,-0.004518,-0.016576,-0.011708,0.007767,-0.018231,0.009922,-0.024940,0.036038,0.013547,-0.019174
Stay_In_Current_City_Years_1,0.019574,-0.000236,0.028831,0.006121,0.001557,-0.003403,-0.002030,0.030400,-0.030400,-0.009230,...,-0.005365,0.004408,0.029456,-0.012011,0.008813,0.003961,-0.029010,-0.007339,-0.024934,0.017269
Stay_In_Current_City_Years_2,0.018551,0.003490,-0.006474,-0.007000,0.000494,0.004742,0.005358,-0.008806,0.008806,0.021599,...,0.012060,-0.006505,-0.022777,0.010043,0.001299,0.006000,0.006424,-0.012531,-0.018273,-0.016026
Stay_In_Current_City_Years_3,-0.030953,-0.000305,-0.013635,-0.010995,-0.000637,0.003398,0.002090,0.011080,-0.011080,0.004379,...,-0.001571,0.000520,-0.025864,0.022324,-0.001446,-0.002402,0.038526,-0.029869,0.012310,0.013472
Stay_In_Current_City_Years_4+,-0.019567,-0.004384,-0.006782,0.006624,0.000846,-0.002331,0.000988,-0.027125,0.027125,-0.020777,...,0.000050,0.016325,0.023735,-0.025675,0.005728,-0.018580,0.014718,0.020366,0.026918,-0.001567
Occupation_0,-0.006057,-0.002256,0.006910,0.002822,-0.003738,-0.003163,-0.010576,0.011648,-0.011648,0.007431,...,-0.055846,-0.093326,-0.045447,-0.087018,-0.057255,-0.083719,-0.106678,-0.042027,-0.047586,-0.097050
Occupation_1,0.056893,-0.006552,0.043117,0.021302,-0.000354,-0.010489,-0.019005,0.094249,-0.094249,-0.036270,...,-0.045057,-0.075296,-0.036667,-0.070207,-0.046194,-0.067545,-0.086069,-0.033907,-0.038393,-0.078301
Occupation_2,0.017432,-0.002180,0.023961,0.013798,-0.003646,-0.009366,-0.013975,0.040584,-0.040584,-0.030396,...,-0.033058,-0.055244,-0.026902,-0.051510,-0.033892,-0.049557,-0.063148,-0.024878,-0.028168,-0.057449
Occupation_3,-0.051561,-0.001576,0.001167,0.008792,0.000949,-0.007386,-0.003095,0.085197,-0.085197,-0.030591,...,-0.026707,-0.044631,-0.021734,-0.041615,-0.027381,-0.040037,-0.051017,-0.020098,-0.022757,-0.046412
Occupation_4,-0.015750,-0.013935,-0.110382,-0.021498,-0.006983,0.001401,-0.003872,-0.000206,0.000206,-0.061644,...,-0.057065,-0.095363,-0.046439,-0.088918,-0.058505,-0.085547,-0.109007,-0.042944,-0.048625,-0.099169
Occupation_5,0.032789,0.006515,-0.010536,-0.009935,-0.002593,0.003937,0.002072,-0.022535,0.022535,-0.025280,...,-0.022070,-0.036882,-0.017961,-0.034389,-0.022627,-0.033085,-0.042159,-0.016609,-0.018806,-0.038354
Occupation_6,0.026592,0.002824,0.016186,0.010269,-0.001938,-0.006722,-0.000290,0.070004,-0.070004,-0.032936,...,-0.028754,-0.048052,-0.023400,-0.044804,-0.029479,-0.043105,-0.054927,-0.021639,-0.024501,-0.049969
Occupation_7,0.012959,0.011345,0.017974,0.000895,0.004404,0.001276,0.011176,-0.062224,0.062224,-0.053319,...,-0.050908,-0.085074,-0.041429,-0.079324,-0.052192,-0.076316,-0.097246,-0.038311,-0.043378,-0.088469
Occupation_8,-0.030669,0.001965,0.015479,-0.009754,-0.000541,0.004485,0.002839,-0.001648,0.001648,-0.002826,...,-0.007787,-0.013014,-0.006337,-0.012134,-0.007984,-0.011674,-0.014876,-0.005860,-0.006636,-0.013533
Occupation_9,-0.020688,-0.006750,0.023498,0.002236,0.003362,-0.003837,-0.013409,0.170091,-0.170091,-0.018072,...,-0.015777,-0.026366,-0.012839,-0.024584,-0.016175,-0.023652,-0.030138,-0.011873,-0.013444,-0.027418
Occupation_10,-0.047445,0.000526,-0.110871,-0.016977,-0.009530,0.003226,-0.009409,0.022558,-0.022558,0.778101,...,-0.022758,-0.038032,-0.018521,-0.035462,-0.023332,-0.034117,-0.043473,-0.017127,-0.019392,-0.039550
Occupation_11,-0.018327,0.002151,-0.007730,0.007070,-0.002619,-0.005543,-0.001464,-0.039946,0.039946,-0.023251,...,1.000000,-0.035956,-0.017510,-0.033526,-0.022059,-0.032255,-0.041101,-0.016192,-0.018334,-0.037391
Occupation_12,-0.015302,-0.000481,0.027601,-0.014237,0.009134,0.017710,0.025995,-0.077104,0.077104,-0.029783,...,-0.035956,1.000000,-0.029261,-0.056027,-0.036864,-0.053902,-0.068685,-0.027059,-0.030638,-0.062486
Occupation_13,-0.027008,0.010099,0.029281,0.020272,0.002397,-0.006602,0.001007,-0.014687,0.014687,-0.018638,...,-0.017510,-0.029261,1.000000,-0.027283,-0.017952,-0.026249,-0.033448,-0.013177,-0.014920,-0.030429
Occupation_14,0.023269,-0.001841,0.001018,-0.007123,0.007263,0.002857,0.010772,0.000399,-0.000399,-0.033639,...,-0.033526,-0.056027,-0.027283,1.000000,-0.034372,-0.050259,-0.064043,-0.025230,-0.028567,-0.058262
Occupation_15,0.036969,-0.002054,0.013363,-0.004792,0.002254,0.008136,0.015416,-0.017588,0.017588,-0.025267,...,-0.022059,-0.036864,-0.017952,-0.034372,1.000000,-0.033069,-0.042138,-0.016600,-0.018796,-0.038335
Occupation_16,0.005952,0.006688,0.028370,0.006437,0.003060,-0.004624,0.005713,-0.043355,0.043355,-0.036946,...,-0.032255,-0.053902,-0.026249,-0.050259,-0.033069,1.000000,-0.061614,-0.024273,-0.027484,-0.056053
Occupation_17,0.000178,0.003999,0.012910,-0.024783,0.009632,0.029622,0.031099,-0.096675,0.096675,-0.045580,...,-0.041101,-0.068685,-0.033448,-0.064043,-0.042138,-0.061614,1.000000,-0.030930,-0.035022,-0.071426
Occupation_18,0.006981,0.005312,0.009975,0.005509,-0.003532,-0.000753,-0.002073,-0.054313,0.054313,-0.018547,...,-0.016192,-0.027059,-0.013177,-0.025230,-0.016600,-0.024273,-0.030930,1.000000,-0.013797,-0.028139
Occupation_19,-0.029552,-0.003145,-0.058008,0.003590,-0.000013,-0.004603,-0.013769,-0.002466,0.002466,0.051955,...,-0.018334,-0.030638,-0.014920,-0.028567,-0.018796,-0.027484,-0.035022,-0.013797,1.000000,-0.031861
Occupation_20,-0.023785,0.001057,0.040947,0.017229,-0.007812,-0.015074,-0.021693,0.009242,-0.009242,-0.042829,...,-0.037391,-0.062486,-0.030429,-0.058262,-0.038335,-0.056053,-0.071426,-0.028139,-0.031861,1.000000

In [260]:
Total['Occupation'] = Total['Occupation'].astype('category')
Total = pd.get_dummies(Total)

In [261]:
Total.shape

(783667, 44)

In [262]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

In [263]:
783666-233598

550068

In [264]:
Total = Total.reset_index()
del Total['index']

In [289]:
Train = Total[0:550068]
Test = Total[550068:]

In [290]:
Train.shape

(550068, 44)

In [291]:
Test.shape

(233599, 44)

In [292]:
df_y = Train['Purchase']
del Train['Purchase']
df_x = Train

In [293]:
lda = LDA(n_components = None)
lda = lda.fit(df_x,df_y)
df_x = lda.transform(df_x)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:442: UserWarning: The priors do not sum to 1. Renormalizing
  UserWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")

In [294]:
del Test['Purchase']

In [295]:
Test = lda.transform(Test)

In [296]:
from sklearn.model_selection import train_test_split

In [297]:
X_Train,X_Test,Y_Train,Y_Test = train_test_split(df_x,df_y,test_size=0.2,random_state=1)

In [298]:
from sklearn.ensemble import RandomForestRegressor

In [299]:
from sklearn.metrics import r2_score, mean_squared_error
from math import sqrt

In [300]:
rfr = RandomForestRegressor(max_depth=8)
rfr.fit(X_Train,Y_Train)
Y_Pred = rfr.predict(X_Test)
print (sqrt(mean_squared_error(Y_Test,Y_Pred)))
Y_Train_Pred = rfr.predict(X_Train)
print (sqrt(mean_squared_error(Y_Train,Y_Train_Pred)))

2959.621946526783
2946.5207275212765

In [301]:
Y_Final_Pred = rfr.predict(Test)

In [302]:
submission = pd.read_csv('Sample_Submission_Tm9Lura.csv')

In [303]:
submission

Empty DataFrame
Columns: [User_ID, Product_ID, Purchase]
Index: []

In [304]:
Submission_Test = pd.read_csv("test.csv")

In [305]:
submission['User_ID'] = Submission_Test['User_ID']
submission['Product_ID'] = Submission_Test['Product_ID']

In [306]:
Y_Final_Pred.shape

(233599,)

In [311]:
submission['Purchase'] = Y_Final_Pred

In [313]:
submission.to_csv('submission.csv')